apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/proxy_set_header: configmap-with-headers
spec:
  rules:
  - host: www.coflnet.com
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service: 
            name: {{ .Chart.Name }}
            port:
              number: 3000
  - host: coflnet.com
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service: 
            name: {{ .Chart.Name }}
            port:
              number: 3000
  - host: coflnet.com
    http:
      paths:
      - path: /.well-known
        pathType: ImplementationSpecific
        backend:
          service:
            name: coflnet-mail-server
            port:
              number: 443
  - host: new.coflnet.com
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service: 
            name: {{ .Chart.Name }}
            port:
              number: 3000
